//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainFoldRide.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Station
    {
        public int id { get; set; }
        public string naptanId { get; set; }
        public string station1 { get; set; }
        public string icsId { get; set; }
        [Display(Name = "Departure Station")]
        public string depStation { get; set; }
        [Display(Name = "Arrival Station")]
        public string arrStation { get; set; }
        [Display(Name = "Fare Cost")]
        public string fare { get; set; }
        [Display(Name = "Calories Burned")]
        public Nullable<int> CaloriesBurned { get; set; }
    }
}
